version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    container_name: circle-link-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TEST_MYSQL_NAME}
      MYSQL_USER: ${TEST_MYSQL_USER}
      MYSQL_PASSWORD: ${TEST_MYSQL_PASS}
    ports:
      - "3306:3306"

  redis-master:
    image: redis:7.0.15
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis/master.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-slave1:
    image: redis:7.0.15
    container_name: redis-slave1
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    volumes:
      - ./redis/slave.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-slave2:
    image: redis:7.0.15
    container_name: redis-slave2
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    volumes:
      - ./redis/slave.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  sentinel1:
    image: redis:7.0.15
    container_name: sentinel1
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: [ "redis-server", "/usr/local/etc/redis/sentinel.conf", "--sentinel" ]

  sentinel2:
    image: redis:7.0.15
    container_name: sentinel2
    ports:
      - "26380:26379"
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: [ "redis-server", "/usr/local/etc/redis/sentinel.conf", "--sentinel" ]

  sentinel3:
    image: redis:7.0.15
    container_name: sentinel3
    ports:
      - "26381:26379"
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: [ "redis-server", "/usr/local/etc/redis/sentinel.conf", "--sentinel" ]
