spring:
  config:
    import:
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-secret.yml
      - classpath:/yaml/application-file.yml
  profiles:
    group:
      local: local, secret, file
      dev: dev, secret ,file
      prod: prod, secret ,file
    active: local #원하는 환경으로 설정(local, dev, prod)

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

file:
  mainPhoto-dir: src/main/resources/static/mainPhoto