<<<<<<< HEAD
# default
spring:
  config:
    import:
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-secret.yml
      - classpath:/yaml/application-file.yml

  profiles:
    active: local #default
    group:
      local:
        - secret
        - file # local + secret + file 실행
      prod:
        - secret
        - file
---
=======
>>>>>>> 9f6d856 (fix: 환경 변수 설정 파일 수정)
spring:
  config:
    activate:
      on-profile: local # local + secret 실행
---
spring:
  config:
    activate:
<<<<<<< HEAD
      on-profile: prod # prod + secret
=======
      on-profile: prod # prod + secret
---
spring:
  config:
    activate:
      on-profile: test
---


# default
spring:
  config:
    import:
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-secret.yml
      - classpath:/yaml/application-file.yml
      - classpath:/yaml/application-test.yml
  profiles:
    active: local #default
    group:
      local:
        - secret
        - file # local + secret + file 실행
      prod:
        - secret
        - file
      test:
        - secret
        - file
>>>>>>> 9f6d856 (fix: 환경 변수 설정 파일 수정)
