spring:
  config:
    import:
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-secret.yml
  profiles:
    group:
      local: local,secret
      dev: dev, secret
      prod: prod, secret
    active: local      #??? ???? ??(local, dev, prod)