# default
spring:
  config:
    import:
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-secret.yml
      - classpath:/yaml/application-file.yml
      - classpath:/yaml/application-test.yml
      - classpath:/yaml/application-security.yml

  profiles:
    active: local #default
    group:
      local:
        - secret
        - file # local + secret + file 실행
        - security
      prod:
        - secret
        - file
        - security
      test:
        - secret
        - file
        - security
springdoc:
  api-docs:
    version: OPENAPI_3_1
server:
  forward-headers-strategy: framework
---
spring:
  config:
    activate:
      on-profile: local # local + secret 실행
---
spring:
  config:
    activate:
      on-profile: prod # prod + secret
---
spring:
  config:
    activate:
      on-profile: test