server:
  port: ${BASIC_PORT}

  error:
    include-exception: false
    include-stacktrace: never
    include-message: always

# log setting
logging:
  level:
    root: info  # 기본 로그 레벨
    com.USWCicrcleLink.server: info  # 우리 프로젝트 관련 로그
    org.springframework.security: off  # Spring Security 내부 로그 숨김
    org.springframework.web: off  # 서블릿 관련 예외 로그 숨김
    org.apache.catalina.core: off  # Tomcat 관련 에러 로그 숨김
    org.springframework: warn  # Spring 내부 로그 최소화
    org.hibernate.SQL: off  # Hibernate SQL 쿼리 로그 비활성화 (배포 환경에서는 사용 안 함)
    org.hibernate.type.descriptor.sql: off  # Hibernate 바인딩 로그 비활성화
    p6spy: off  # SQL 로깅 라이브러리 로그 비활성화

#email url
email:
  config:
    baseUrl: ${PROD_SERVER_URL}

firebase:
  config-path: ${SERVER_FIREBASE_CONFIG_PATH}

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PROD_MYSQL_HOST}:${PROD_MYSQL_PORT}/${PROD_MYSQL_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${PROD_MYSQL_USER}
    password: ${PROD_MYSQL_PASS}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# CORS 설정 추가
cors:
  allowed-origins: ${PROD_SERVER_ALLOWED_ORIGINS}

# 쿠키 설정 추가
security:
  cookie:
    secure: true

cloud:
  aws:
    s3:
      region: ap-northeast-2
      credentials: instance-profile
      bucket: ${SERVER_AWS_S3_BUCKET}
    stack:
      auto: false