server:
  port: 8080
  base:
    url: "http://localhost:8080"

logging:
  level:
    com:
      USWCicrcleLink:
        server: debug

email:
  config:
    baseUrl: "http://localhost:8080"

spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/CircleLink
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  firebase:
    config-path:${LOCAL_FIREBASE_CONFIG_PATH}

cloud:
  aws:
    s3:
      bucket: ${LOCAL_AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
