server:
  port: ${BASIC_PORT}

# log setting
logging:
  level:
    com:
      USWCicrcleLink:
        server: debug

#email url
email:
  config:
    baseUrl: ${PROD_SERVER_URL}

spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PROD_MYSQL_HOST}:${PROD_MYSQL_PORT}/${PROD_MYSQL_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${PROD_MYSQL_USER}
    password: ${PROD_MYSQL_PASS}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  firebase:
    config-path:${SERVER_FIREBASE_CONFIG_PATH}

cloud:
  aws:
    s3:
      bucket: ${SERVER_AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false