server:
  port: ${BASIC_PORT}
  base:
    url: ${SERVER_URL}

# log setting
logging:
  level:
    com:
      USWCicrcleLink:
        server: debug

#email url
email:
  config:
    baseUrl: ${SERVER_URL}

spring:
  config:
    activate:
      on-profile: prod

  firebase:
    config-path:${SERVER_FIREBASE_CONFIG_PATH}

cloud:
  aws:
    s3:
      bucket: prod-sw-circle-link-upload-files
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SERVER_MYSQL_URL}
    username: ${SERVER_MYSQL_USERNAME}
    password: ${SERVER_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${SERVER_REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${SERVER_REDIS_PASSWORD}