server:
  port: ${BASIC_PORT}

# log setting
logging:
  level:
    com:
      USWCicrcleLink:
        server: debug
    com.USWCicrcleLink.server: warn

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_SQL_URL}
    username: ${DEV_SQL_USERNAME}
    password: ${DEV_SQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${REDIS_PORT}