server:
  port: ${BASIC_PORT}
  base:
    url: ${SERVER_URL}

# log setting
logging:
  level:
    com:
      USWCicrcleLink:
        server: debug

#email url
email:
  config:
    baseUrl: ${SERVER_URL}

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SERVER_SQL_URL}
    username: ${SERVER_SQL_USERNAME}
    password: ${SERVER_SQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${SERVER_REDIS_HOST}127.0.0.1
      port: ${REDIS_PORT}
      password: ${SERVER_REDIS_PASSWORD}