server:
  port: 8080

# log setting
logging:
  level:
    com:
      USWRandomChat:
        backend: warn

#email url
email:
  config:
    baseUrl: "http://43.200.140.186:8080"

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.200.140.186:3306/circle_link_prod?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: circlelink
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

#  data:
#    redis:
#      host: prod-redis-server
#      port: 6379