spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nkdy50315031@gmail.com
    password: zczxsylqqelzckrq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret:
    key: FC7DEE6E587E7E7EDE7A8E7DEEE6E6EF7E6DE7E7E6E76E7E6E6E7E76E6DEEF7