spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: file

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      resolve-lazily: true

file:
  allowed-extensions: jpg,jpeg,png