server:
  port: 8080
  base:
    url: "http://localhost:8080"

logging:
  level:
    root: info  # 기본 로그
    com:
      USWCicrcleLink:
        server: debug  # Local 환경
    org.springframework: debug  # 스프링 내부 로그
    org.hibernate.SQL: debug  # Hibernate SQL 로그
    org.hibernate.type.descriptor.sql: trace  # Hibernate SQL 바인딩 로그
    p6spy: debug  # p6spy (SQL 로깅 라이브러리) 로그

email:
  config:
    baseUrl: "http://localhost:8080"

firebase:
  config-path: ${LOCAL_FIREBASE_CONFIG_PATH}

spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/CircleLink
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


# CORS 설정 추가
cors:
  allowed-origins: ${LOCAL_SERVER_ALLOWED_ORIGINS}

  # 쿠키 설정 추가
security:
  cookie:
    secure: false

cloud:
  aws:
    s3:
      region: ap-northeast-2
      credentials: default
      bucket: ${LOCAL_AWS_S3_BUCKET}
    stack:
      auto: false