server:
  port: 8080

# log setting
logging:
  level:
    com:
      USWRandomChat:
        backend: debug

#email url
email:
  config:
    baseUrl: "http://localhost:8080"

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/CircleLink
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379