spring:
  config:
    activate:
      on-profile: file

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      resolve-lazily: true

file:
  allowed-extensions: jpg,jpeg,png