server:
  port: ${BASIC_PORT}

# log setting
logging:
  level:
    com:
      USWCircleLink:
        server: debug

#email url
email:
  config:
    baseUrl: ${PROD_SERVER_URL}

firebase:
  config-path:${SERVER_FIREBASE_CONFIG_PATH}

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PROD_MYSQL_HOST}:${PROD_MYSQL_PORT}/${PROD_MYSQL_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${PROD_MYSQL_USER}
    password: ${PROD_MYSQL_PASS}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# CORS 설정 추가
cors:
  allowed-origins: ${PROD_SERVER_ALLOWED_ORIGINS}

# 쿠키 설정 추가
security:
  cookie:
    secure: true

cloud:
  aws:
    s3:
      region: ap-northeast-2
      credentials: instance-profile
      bucket: ${SERVER_AWS_S3_BUCKET}
    stack:
      auto: false