server:
  port: ${BASIC_PORT}
  base:
    url: ${LOCAL_URL}

# log setting
logging:
  level:
    com:
      USWCicrcleLink:
        server: debug

#email url
email:
  config:
    baseUrl: ${LOCAL_URL}

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}