server:
  port: 8080
  base:
    url: "http://localhost:8080"

  error:
    include-exception: true
    include-stacktrace: always
    include-message: always

logging:
  level:
    root: info
    # 서비스
    com.USWCicrcleLink.server: debug
    # 스프링 프레임워크
    org.springframework: info
    org.springframework.web: debug
    org.springframework.security: info
    # JPA
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace  # 바인딩된 SQL 파라미터
    org.hibernate.type: info  # Hibernate 데이터 타입 변환 로그
    # tomcat, 웹 서버
    org.apache.catalina.core: info
    # DB 쿼리
    p6spy: debug

email:
  config:
    baseUrl: "http://localhost:8080"

firebase:
  config-path: ${LOCAL_FIREBASE_CONFIG_PATH}

spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/CircleLink
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


# CORS 설정 추가
cors:
  allowed-origins: ${LOCAL_SERVER_ALLOWED_ORIGINS}

  # 쿠키 설정 추가
security:
  cookie:
    secure: false

cloud:
  aws:
    s3:
      region: ap-northeast-2
      credentials: default
      bucket: ${LOCAL_AWS_S3_BUCKET}
    stack:
      auto: false